### ISSUE TITLE
Can't generate access token

### ISSUE THREAD

**Issue by BUCKFAE** [pkmn-api/pkmnapi#3]
Hello! I would love to extract data from a gen1 game and use this data for my master thesis. However, i am unable to create an access token as described in [Creating an Access Token](https://www.pkmnapi.com/getting-started/creating-an-access-token/):
```bash
[15:19:03] buckfae :: arch  ➜  ~ » cat get_token.sh
curl \
    -X POST \
    -H 'Content-Type: application/json' \
    -d '{
    "data": {
        "type": "access_tokens",
        "attributes": {
            "email_address": "<my-actual-email>"
        }
    }
}' \
    https://api.pkmnapi.com/v1/access_tokens
[15:19:05] buckfae :: arch  ➜  ~ » ./get_token.sh
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

The js-example yields a similar issue for me. I tried multiple of my email-addresses and checked the spam folders.

It would be awesome if i could use this API, thank you in advance!

**Comment by kevinselwyn** [comment]
@BUCKFAE Would you mind trying again? The Heroku deployment had become misconfigured. I was able to restart it and successfully generate an access token.

On a side note, I'd love to read your master thesis when it's complete! Send me an email when it's ready? Best of luck!

**Comment by BUCKFAE** [comment]
@kevinselwyn creating an access key worked, thank you!

However, i can't upload my ROM:
```
[17:18:19] buckfae :: arch  ➜  pokemontoknowledgegraph/pokegraph/scraping ‹master*› » cat upload_rom.sh
#!/bin/bash

curl \
    -X POST \
    -H 'Authorization: Bearer <key>' \
    --data-binary <path> \
    https://api.pkmnapi.com/v1/roms                                                                                               
  
[17:18:21] buckfae :: arch  ➜  pokemontoknowledgegraph/pokegraph/scraping ‹master*› » ./upload_rom.sh
{"data":{"id":"error_roms_invalid_rom","type":"errors","attributes":{"message":"Invalid ROM provided"}}}
```

I am pretty sure that my rom is valid because i can play it on an emulator and the checksum matches the checksum provided at the [pokered repo](https://github.com/pret/pokered/tree/master)

**Comment by kevinselwyn** [comment]
@BUCKFAE Can you make sure there's an `@` before the path? Check out the [documentation](https://www.pkmnapi.com/getting-started/uploading-a-rom/) which has:

```
--data-binary @path/to/rom.gb
```

**Comment by BUCKFAE** [comment]
> @BUCKFAE Can you make sure there's an `@` before the path? Check out the [documentation](https://www.pkmnapi.com/getting-started/uploading-a-rom/) which has:
> 
> ```
> --data-binary @path/to/rom.gb
> ```

I figured it out:
I had to use the absolute path instead of using tilde expansion:
```
---data-binary @/home/<user>/Documents/dump.gb
```
Worked. Thank you very much!

**Comment by BUCKFAE** [comment]
Now that i played around a bit with the API there are unfortunately some things missing that would fit my use-case of building a knowledge graph of the game. 

## Map Information
- The `/maps`-endpoint does not return a name of the map (like `Route 01` or `house at XY`) but only an ID. Were can i find a mapping from id -> name?
- I would also love to have a mapping of "adjacent" locations, like on serebii. E.g. North of Route1 is Viridian City.
- For encounters, i could only find the general encounter rate and which pokemon can be encountered but not the individual chance of getting each Pokemon (e.g. Pidgey 55% Chance on Route 1)
- It would be cool to have a list of items that can be picked up at this location

## Trainer
- Here, i could also only find the ID of the trainer but not the exact location of the trainer. E.g. Trainer with ID1 is located at Route 3 and has two level nine Pidgeys.
- For a given trainer only the list pokemon the trainer has is returned but i could not find a way to get the exact moves this pokemon of this trainer has

## Mart Items
- I could also not find where this mart is located

## Trades
- There seems also to be only an ID of the trade but i can't figure out *where* this trade is on the map


I am fully aware that this endpoint was not at all designed to fit my rather uncommon project. If there is no simple way to extract the data from the ROM i'd get as much as i can from the API and scrape the rest from various websites.
Thank you very much in advance!

**Comment by kevinselwyn** [comment]
@BUCKFAE Thanks for the feature requests! There are definitely some good ones in there. I've created individual issues to address some of these requests.

I'll be sure to let you know when I get to them.
